name: CI
on:
  push:
    branches:
      - main
      - release-v*
  pull_request:
    branches:
      - main
      - release-v*
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ["6.0.x", "7.0.x", "8.0.x", "9.0.x"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore Deepgram.sln
      - name: Run tests
        run: dotnet test Deepgram.sln
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.x.x"
      - name: Install dependencies
        run: dotnet restore Deepgram.sln
      - name: Build
        run: dotnet build Deepgram.sln --configuration Release --no-restore
